In [1]:
a = [1,2,3,4]
b=[2,3,4,5]
a

[1, 2, 3, 4]

In [4]:
import numpy as np

In [6]:
b=np.array([2,3,4,5])
a=np.array([1,2,3,4])
a*b

array([ 2,  6, 12, 20])

In [7]:
np.array([1,2,3,4],dtype ="float32") #listenin tipini belirtme

array([1., 2., 3., 4.], dtype=float32)

In [8]:
np.array([1,2,3,4],dtype ="int")

array([1, 2, 3, 4])

In [9]:
np.zeros(10,dtype=int) #0lardan oluşan liste

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((3,5),dtype=int) #birlerden oluşan matris

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.full((3,5),3) #diziyi sonda belirtilenlerle doldur

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [13]:
np.arange(0,31,3) #0dan 31e 3er artacak şekilde doğrusal dizi

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [14]:
np.linspace(0,1,10) #0 ile 1 arası 10 tane değer tek boyutlu

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
np.random.normal(10,4,(3,4)) #3 satır 4 sütun ort=10 standart sapma=4 

array([[10.11978631, 16.59300253, 13.26454515,  5.35277092],
       [12.26451651,  3.46248754,  5.28939765,  6.64513875],
       [13.49193054, 10.71172333, 14.38214771, 10.04852185]])

In [17]:
np.random.randint(0,10,(3,3)) #rastgele 0-10 arası 3e 3lük

array([[7, 1, 5],
       [3, 9, 5],
       [7, 6, 9]])

**ndim** -> kaç boyutlu dizi? 
**shape**-> boyut bilgisi(kaç elemanlı)
**size** -> toplam eleman sayısı
**dtype**-> array veri tipi


In [21]:
a=np.random.normal(4,2,(3,3))
a.ndim

TypeError: normal() got an unexpected keyword argument 'dtype'

In [19]:
a.shape

(3, 3)

In [20]:
a.dtype

dtype('float64')

In [23]:
b=np.random.randint(10, size=(3,5))
b.shape

(3, 5)

In [26]:
np.arange(1,10).reshape((3,3)) #tek boyuttan 2 boyuta döndürdü

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**ARRAY BİRLEŞTİRME**

In [27]:
a=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([a,y]) #dizileri birleştirir

array([1, 2, 3, 4, 5, 6])

In [34]:
m=np.array([[1,2,3],[4,5,6]])
#axis 1=satır bazındabirleştirme, axis 0= sutun olarak ekleme
np.concatenate([m,m],axis=0) 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

**ARRAY AYIRMA**

In [38]:
a,b,c = np.split(a,[1,2]) # birinci 1 e kadar diğeri 2 ye digerleri de sona

In [39]:
a

array([1])

In [42]:
d=np.arange(16).reshape(4,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
np.vsplit(d, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [45]:
np.sort(d,axis=1) #kalıcı olmadan sıralar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
d[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
d[0::2] 

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [48]:
d[:,1] #satırın hepsi, 1. sutunu al

array([ 1,  5,  9, 13])

In [49]:
v=np.array([1,2,3,4])
v[v<3] #fancy index


array([1, 2])

In [50]:
np.cos(180)

-0.5984600690578581

In [ ]:
 #cheatsheet --> google da aratırsan her şeyi söyler

**NUMPY İLE 2 BİLİNMEYENLİ DENKLEM**

5*x0 + x1=12
x0+3*x1=10


In [52]:
a=np.array([[5,1],[1,3]]) #bilinmeyenlerin katsayısını listeye koy
b=np.array([12,10]) # eşitliklerin karşısı
x=np.linalg.solve(a,b)
x
#x0 ve x1 i buldu

array([1.85714286, 2.71428571])