In [1]:
import pandas as pd

In [73]:
pd.Series([10,88,3,4,5])#indexli tutulur

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [4]:
seri = pd.Series([10,88,3,4,5])

In [5]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [74]:
seri.ndim #kaç boyutlu

1

In [7]:
seri.values

array([10, 88,  3,  4,  5], dtype=int64)

In [75]:
seri.head(3) #ilk 3ü

reg    132
abc    211
kkp    110
dtype: int64

In [11]:
seri.tail(3)#sondan3

2    3
3    4
4    5
dtype: int64

In [18]:
seri = pd.Series([99,44,1,12], index=["a","b","c","d"])

In [19]:
seri

a    99
b    44
c     1
d    12
dtype: int64

In [20]:
seri["a":"c"]

a    99
b    44
c     1
dtype: int64

In [21]:
sozluk={"reg":10,"abc":4,"cart":12}
seri = pd.Series(sozluk)
seri

reg     10
abc      4
cart    12
dtype: int64

In [23]:
pd.concat([seri,seri]) # birleştirme

reg     10
abc      4
cart    12
reg     10
abc      4
cart    12
dtype: int64

In [28]:
seri = pd.Series([132,211,110,114],
                index=["reg","abc","kkp","dnm"])
seri

reg    132
abc    211
kkp    110
dnm    114
dtype: int64

In [29]:
seri.size

4

In [32]:
seri.keys

<bound method Series.keys of reg    132
abc    211
kkp    110
dnm    114
dtype: int64>

In [34]:
"reg" in seri

True

**PANDAS DATAFRAME**

In [38]:
l = [13,2,32,4,78]
l

[13, 2, 32, 4, 78]

In [39]:
pd.DataFrame(l,columns=["degisken_ismi"])

degisken_ismi
0             13
1              2
2             32
3              4
4             78

In [41]:
import numpy as np
m=np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
df=pd.DataFrame(m,columns = ["var1","var2","var3"])

In [72]:
df.head()

var1  var2  var3
0    20     2     1
1     1    28    22
2     3    11    10
3     7    14    12
4    24    21    11

In [47]:
df.columns=("degis1","degis2","degis3")
df

degis1  degis2  degis3
0       1       2       3
1       4       5       6
2       7       8       9

In [48]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['degis1', 'degis2', 'degis3'], dtype='object')]

In [49]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
df

degis1  degis2  degis3
0       1       2       3
1       4       5       6
2       7       8       9

**GÖZLEM VE DEĞİŞKEN SEÇİMİ: LOC VE ILOC** 

In [51]:
m=np.random.randint(1,30,size=(10,3))
df=pd.DataFrame(m, columns=["var1","var2","var3"])
df

var1  var2  var3
0    20     2     1
1     1    28    22
2     3    11    10
3     7    14    12
4    24    21    11
5    11    23    10
6     4    25    29
7    27    29     1
8    17    18    25
9    12    24    18

In [ ]:
#loc : seçim yapmak için kullanılır

In [52]:
df.loc[0:3] #3ü de alır

var1  var2  var3
0    20     2     1
1     1    28    22
2     3    11    10
3     7    14    12

In [53]:
#iloc :indexleme mantığıyla #3 dahil değil
df.iloc[0:3]

var1  var2  var3
0    20     2     1
1     1    28    22
2     3    11    10

In [54]:
df[df.var1>5] #var1de 5 ten büyük olanlari filtreler

var1  var2  var3
0    20     2     1
3     7    14    12
4    24    21    11
5    11    23    10
7    27    29     1
8    17    18    25
9    12    24    18

In [56]:
df[(df.var1>5) & (df.var2>5)]

var1  var2  var3
3     7    14    12
4    24    21    11
5    11    23    10
7    27    29     1
8    17    18    25
9    12    24    18

In [57]:
df1=df+99
df1

var1  var2  var3
0   119   101   100
1   100   127   121
2   102   110   109
3   106   113   111
4   123   120   110
5   110   122   109
6   103   124   128
7   126   128   100
8   116   117   124
9   111   123   117

In [62]:
pd.concat([df,df1], ignore_index=True) #birleştirme yapar

var1  var2  var3
0     20     2     1
1      1    28    22
2      3    11    10
3      7    14    12
4     24    21    11
5     11    23    10
6      4    25    29
7     27    29     1
8     17    18    25
9     12    24    18
10   119   101   100
11   100   127   121
12   102   110   109
13   106   113   111
14   123   120   110
15   110   122   109
16   103   124   128
17   126   128   100
18   116   117   124
19   111   123   117

In [66]:
#bir değişken her iki veri setinde yoksa concatte hata verir (NaN)
df1.columns=["var8","var2","var3"]

In [67]:
df1

var8  var2  var3
0   119   101   100
1   100   127   121
2   102   110   109
3   106   113   111
4   123   120   110
5   110   122   109
6   103   124   128
7   126   128   100
8   116   117   124
9   111   123   117

In [77]:
pd.concat([df,df1], join="inner") #inner ortak columnları birleştirir, exes olsa secilene gore olurdu

var2  var3
0     2     1
1    28    22
2    11    10
3    14    12
4    21    11
5    23    10
6    25    29
7    29     1
8    18    25
9    24    18
0   101   100
1   127   121
2   110   109
3   113   111
4   120   110
5   122   109
6   124   128
7   128   100
8   117   124
9   123   117

In [76]:
pd.merge(df1,df, on="var2") #birleştirme

Empty DataFrame
Columns: [var8, var2, var3_x, var1, var3_y]
Index: []

In [78]:
import seaborn as sns

In [80]:
df=sns.load_dataset("planets")
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [81]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [83]:
df.shape

(1035, 6)

In [84]:
df.ndim

2

In [87]:
df.mean

<bound method NDFrame._add_numeric_operations.<locals>.mean of                method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]>

In [88]:
df["mass"].mean() #ortalama hesaplama

2.6381605847953216

In [89]:
df["mass"].min()

0.0036

In [90]:
df["mass"].max()

25.0

In [91]:
df["mass"].count()#eleman sayma

513

In [92]:
df["mass"].sum() # elemanları toplama

1353.37638

In [93]:
df["mass"].std()#standart sapma

3.8186166509616046

In [94]:
df.describe().T # hepsi bir arada

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0